In [2]:
import torch
print(f"Torch Version :",torch.__version__)

Torch Version : 2.4.0


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device Name : ", torch.cuda.get_device_name(0))
else:
    print("CPU")

GPU is available
Device Name :  NVIDIA GeForce MX250


# Creating Tensor

In [4]:
type(torch.empty(2,3))

torch.Tensor

In [5]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#change torch value
torch.rand(2, 3)

tensor([[0.8033, 0.2259, 0.5158],
        [0.2848, 0.4862, 0.5477]])

In [9]:
torch.rand(2, 3)

tensor([[0.7958, 0.4697, 0.0252],
        [0.4368, 0.9688, 0.4025]])

In [10]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#Fixed torch value
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.tensor([[1, 2, 3],[4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [14]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
torch.full((5, 3),10)

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

# Tensors Shape

In [17]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(type(x))

<class 'torch.Tensor'>


In [18]:
torch.empty_like(x)

tensor([[4951241787696,             0,             0],
        [            0,             0,             0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
# torch.rand_like(x)

# x contains integer values, but torch.rand_like() only works with float values

# Tensor Data Types

In [22]:
x.dtype

torch.int64

In [23]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [26]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Mathematical Operation of Tensor

In [27]:
a = torch.tensor([1, 2, 3])

In [28]:
a + 2

tensor([3, 4, 5])

In [29]:
a - 2

tensor([-1,  0,  1])

In [30]:
a * 2

tensor([2, 4, 6])

In [31]:
a / 2

tensor([0.5000, 1.0000, 1.5000])

In [32]:
a //2

tensor([0, 1, 1])

In [33]:
a ** 2

tensor([1, 4, 9])

In [34]:
a % 2

tensor([1, 0, 1])

In [35]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [36]:
a + b

tensor([5, 7, 9])

In [37]:
a - b

tensor([-3, -3, -3])

In [38]:
a * b

tensor([ 4, 10, 18])

In [39]:
a / b

tensor([0.2500, 0.4000, 0.5000])

In [40]:
a // b

tensor([0, 0, 0])

In [41]:
a ** b

tensor([  1,  32, 729])

In [42]:
c = torch.neg(a)
c

tensor([-1, -2, -3])

In [43]:
torch.abs(c)

tensor([1, 2, 3])

In [44]:
x = torch.tensor([1.6, 2.2, 3.5],)
x

tensor([1.6000, 2.2000, 3.5000])

In [45]:
torch.round(x)

tensor([2., 2., 4.])

In [46]:
torch.floor(x)

tensor([1., 2., 3.])

In [47]:
torch.ceil(x)

tensor([2., 3., 4.])

In [48]:
torch.clamp(x, min=2, max=3)

tensor([2.0000, 2.2000, 3.0000])

# Reduction Operation

In [49]:
x = torch.tensor([[4, 2, 3],[1, 5, 6]])
x = x.to(torch.float32)
x

tensor([[4., 2., 3.],
        [1., 5., 6.]])

In [50]:
torch.sum(x)

tensor(21.)

In [51]:
torch.sum(x,dim=0)

tensor([5., 7., 9.])

In [52]:
torch.mean(x)

tensor(3.5000)

In [53]:
torch.median(x)

tensor(3.)

In [54]:
torch.max(x)

tensor(6.)

In [55]:
torch.min(x)

tensor(1.)

In [56]:
torch.prod(x)

tensor(720.)

In [57]:
torch.std(x)

tensor(1.8708)

In [58]:
torch.var(x)

tensor(3.5000)

In [59]:
torch.argmax(x)

tensor(5)

In [60]:
torch.argmin(x)

tensor(3)

In [61]:
x = torch.tensor([[4.0, 2.0, 3.0],[1.0, 5.0, 6.0]])
y = torch.tensor([[6.0, 2.0],[1.0, 2.0],[3.0, 3.0]])

In [62]:
torch.transpose(x, 0, 1)

tensor([[4., 1.],
        [2., 5.],
        [3., 6.]])

In [63]:
torch.matmul(x, y)

tensor([[35., 21.],
        [29., 30.]])

In [64]:
x = torch.tensor([1, 2])
y = torch.tensor([4, 5])

torch.dot(x, y)

tensor(14)

In [65]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

torch.det(x)

tensor(-2.)

In [66]:
torch.inverse(x)


tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [67]:
torch.log(x)

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])

In [68]:
torch.exp(x)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])

In [69]:
torch.sqrt(x)

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

In [70]:
torch.sigmoid(x)

tensor([[0.7311, 0.8808],
        [0.9526, 0.9820]])

In [71]:
torch.relu(x)

tensor([[1., 2.],
        [3., 4.]])

## Implace operation(fixed)

In [72]:
x.relu_()

tensor([[1., 2.],
        [3., 4.]])

In [73]:
x

tensor([[1., 2.],
        [3., 4.]])

# Copying a Tensor

In [74]:
a = x

In [75]:
id(a), id(x)    

(2173644680288, 2173644680288)

In [76]:
a = x.clone()

In [77]:
a

tensor([[1., 2.],
        [3., 4.]])

In [78]:
id(a),id(x)

(2173644684768, 2173644680288)

# Tensor Operation on GPU

In [79]:
torch.cuda.is_available()

True

In [80]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce MX250'

In [81]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [82]:
# creating a new tensor on the GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [83]:
# moving an exising tensor to the GPU
x = torch.rand((2,3))
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [84]:
x = x.to(device)
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]], device='cuda:0')

In [85]:
x + 2

tensor([[2.2239, 2.3023, 2.1784],
        [2.8238, 2.5557, 2.9770]], device='cuda:0')

In [86]:
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time
print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)


Time on CPU: 14.6982 seconds
Time on GPU: 4.3916 seconds

Speedup (CPU time / GPU time): 3.3469267119907173


# Reshaping Tensor 

In [87]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
# reshape
a = a.reshape(2,2,2,2)
a

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [89]:
a.shape

torch.Size([2, 2, 2, 2])

In [90]:
# Flatten
a = a.flatten()
a

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
a.shape

torch.Size([16])

In [92]:
a = torch.rand(2,3,4)
a

tensor([[[0.0917, 0.0962, 0.9415, 0.8114],
         [0.6297, 0.3090, 0.9336, 0.9341],
         [0.3890, 0.4796, 0.2530, 0.2963]],

        [[0.0637, 0.2825, 0.0670, 0.7522],
         [0.5635, 0.2734, 0.1240, 0.7792],
         [0.7891, 0.5838, 0.0878, 0.0257]]])

In [93]:
a.shape

torch.Size([2, 3, 4])

In [94]:
# permutaion
a = a.permute(1,2,0)
a

tensor([[[0.0917, 0.0637],
         [0.0962, 0.2825],
         [0.9415, 0.0670],
         [0.8114, 0.7522]],

        [[0.6297, 0.5635],
         [0.3090, 0.2734],
         [0.9336, 0.1240],
         [0.9341, 0.7792]],

        [[0.3890, 0.7891],
         [0.4796, 0.5838],
         [0.2530, 0.0878],
         [0.2963, 0.0257]]])

In [95]:
a.shape

torch.Size([3, 4, 2])

In [96]:
# unsqeeze (for image)
a = torch.rand(226,226,3)
a.shape

torch.Size([226, 226, 3])

In [97]:
a = a.unsqueeze(0) # batch size
a.shape

torch.Size([1, 226, 226, 3])

In [98]:
a.squeeze().shape

torch.Size([226, 226, 3])

# NumPy and PyTorch

In [99]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [100]:
type(a)

torch.Tensor

In [101]:
a = a.numpy()
a

array([1, 2, 3], dtype=int64)

In [102]:
type(a)

numpy.ndarray

In [103]:
a = torch.from_numpy(a)
a

tensor([1, 2, 3])

In [104]:
type(a)

torch.Tensor

# Next Topics: PyTorch Autograd
# Thank YOu