In [18]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [20]:
df.shape

(569, 33)

In [21]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [22]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [23]:
df.shape

(569, 31)

# Train - Test - Split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [25]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
X_train

array([[-0.45790336,  1.11562877, -0.31398503, ...,  1.62004903,
         2.29683658,  6.71369463],
       [-0.15350458, -1.16421336, -0.1710223 , ...,  0.22669879,
         0.11227754, -0.62529886],
       [-0.20987472, -0.81093204, -0.21075693, ...,  0.86141365,
         0.97729372,  0.95282138],
       ...,
       [-0.8243093 ,  0.49620885, -0.84733024, ..., -1.06902626,
         0.11070479, -0.69928174],
       [-0.57346215, -1.10062272, -0.55689879, ..., -0.73020942,
        -0.24945649, -0.05845939],
       [ 0.46938552, -0.01958188,  0.63350149, ...,  1.50670709,
         2.10653302,  1.13777859]])

In [27]:
X_test

array([[ 1.10636815,  0.2960161 ,  1.09638942, ...,  0.53045519,
         0.54321288, -0.42619785],
       [-1.52583574, -1.14301648, -1.52445744, ..., -1.71976011,
        -0.49323378, -0.30488768],
       [ 0.61031088,  0.04871918,  0.74410303, ...,  0.96266578,
         0.64858757,  0.39577377],
       ...,
       [-1.43310686, -1.15479253, -1.44498819, ..., -1.50985084,
         0.13429614, -0.32882332],
       [-0.69465796, -0.2645236 , -0.62489825, ...,  0.4201357 ,
        -0.38628632,  0.46866867],
       [-0.17323413, -1.23486963, -0.1767572 , ...,  0.29772641,
         0.50546671,  0.49913221]])

# Label Encoding

In [28]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [29]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,

In [30]:
y_test

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0])

# Numpy arrays to PyTorch tensors

In [31]:
type(X_train)

numpy.ndarray

In [32]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [33]:
type(X_train)

torch.Tensor

In [34]:
X_train.shape

torch.Size([455, 30])

In [35]:
y_train.shape

torch.Size([455])

# Defining Model

In [37]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
    return loss

# Important Parameters

In [53]:
learning_rate = 0.1
epochs = 51

# Training Pipeline

In [55]:
# create model
model = MySimpleNN(X_train)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train)

  # loss calculate
  loss = model.loss_function(y_pred, y_train)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  if epoch % 10 == 0:
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 0, Loss: 3.5912259407917864
Epoch: 10, Loss: 2.1978771135804824
Epoch: 20, Loss: 0.9801274682693126
Epoch: 30, Loss: 0.7731040483932108
Epoch: 40, Loss: 0.7202626739797738
Epoch: 50, Loss: 0.6960553253400821


In [57]:
model.weights

tensor([[ 0.2407],
        [ 0.0269],
        [ 0.2722],
        [ 0.2335],
        [ 0.0460],
        [-0.0029],
        [-0.0762],
        [ 0.1809],
        [ 0.1501],
        [ 0.1852],
        [-0.6047],
        [ 0.0898],
        [ 0.2548],
        [ 0.1049],
        [ 0.1234],
        [-0.0543],
        [-0.3017],
        [ 0.0392],
        [-0.0319],
        [ 0.3888],
        [-0.2752],
        [-0.0806],
        [ 0.1397],
        [ 0.0118],
        [-0.1674],
        [-0.2513],
        [ 0.1171],
        [-0.3711],
        [ 0.0784],
        [-0.0515]], dtype=torch.float64, requires_grad=True)

In [58]:
model.bias

tensor([-0.2946], dtype=torch.float64, requires_grad=True)

# Evaluation

In [56]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test).float().mean()
  print(f'Accuracy: {accuracy.item():.3f}')


Accuracy: 0.621


# Thank You